export const SETTLEMENT_ERROR_EMAIL: string[] = [
  // 'tarun.k@edviron.com',
  // 'raj.barmaiya@edviron.com',
  `manish.verma@edviron.com`,
  // `souvik.hazra@edviron.com`,
];

export const RECON_ERROR_EMAIL: string[] = [
  // 'tarun.k@edviron.com',
  // 'raj.barmaiya@edviron.com',
  `manish.verma@edviron.com`,
  `souvik.hazra@edviron.com`,
];

export const VENDOR_STATUS_EMAIL: string[] = [
  // 'tarun.k@edviron.com',
  // 'raj.barmaiya@edviron.com',
  `manish.verma@edviron.com`,
  `souvik.hazra@edviron.com`,
];

export const DISPUT_INVOICE_MAIL_GATEWAY: string[] = [
  // 'raj.barmaiya@edviron.com',
  `manish.verma@edviron.com`,
  `souvik.hazra@edviron.com`,
];

export const VENDOR_CREATE_ALERT_EMAIL: string[] = [
  'tarun.k@edviron.com',
  'raj.barmaiya@edviron.com',
  // `manish.verma@edviron.com`,
  // `souvik.hazra@edviron.com`,
];


export enum CurrencyCode {
  AFN = 'AFN',
  ALL = 'ALL',
  DZD = 'DZD',
  AOA = 'AOA',
  ARS = 'ARS',
  AMD = 'AMD',
  AWG = 'AWG',
  AUD = 'AUD',
  AZN = 'AZN',
  BSD = 'BSD',
  BHD = 'BHD',
  BDT = 'BDT',
  BBD = 'BBD',
  BZD = 'BZD',
  BMD = 'BMD',
  BTN = 'BTN',
  BOB = 'BOB',
  BAM = 'BAM',
  BWP = 'BWP',
  BRL = 'BRL',
  BND = 'BND',
  BGN = 'BGN',
  BIF = 'BIF',
  KHR = 'KHR',
  CAD = 'CAD',
  CVE = 'CVE',
  KYD = 'KYD',
  XAF = 'XAF',
  XPF = 'XPF',
  CLP = 'CLP',
  COP = 'COP',
  KMF = 'KMF',
  CDF = 'CDF',
  CRC = 'CRC',
  CZK = 'CZK',
  DKK = 'DKK',
  DJF = 'DJF',
  DOP = 'DOP',
  XCD = 'XCD',
  EGP = 'EGP',
  ERN = 'ERN',
  SZL = 'SZL',
  ETB = 'ETB',
  EUR = 'EUR',
  FKP = 'FKP',
  FJD = 'FJD',
  GMD = 'GMD',
  GEL = 'GEL',
  GHS = 'GHS',
  GIP = 'GIP',
  GTQ = 'GTQ',
  GNF = 'GNF',
  GYD = 'GYD',
  HTG = 'HTG',
  HNL = 'HNL',
  HKD = 'HKD',
  HUF = 'HUF',
  ISK = 'ISK',
  INR = 'INR',
  IDR = 'IDR',
  IQD = 'IQD',
  JMD = 'JMD',
  JPY = 'JPY',
  JOD = 'JOD',
  KZT = 'KZT',
  KES = 'KES',
  KWD = 'KWD',
  KGS = 'KGS',
  LAK = 'LAK',
  LBP = 'LBP',
  LRD = 'LRD',
  LYD = 'LYD',
  MOP = 'MOP',
  MKD = 'MKD',
  MGA = 'MGA',
  MWK = 'MWK',
  MYR = 'MYR',
  MVR = 'MVR',
  MRU = 'MRU',
  MUR = 'MUR',
  MXN = 'MXN',
  MDL = 'MDL',
  MNT = 'MNT',
  MAD = 'MAD',
  MZN = 'MZN',
  NAD = 'NAD',
  NPR = 'NPR',
  ILS = 'ILS',
  TWD = 'TWD',
  NZD = 'NZD',
  NIO = 'NIO',
  NGN = 'NGN',
  NOK = 'NOK',
  PGK = 'PGK',
  PYG = 'PYG',
  PEN = 'PEN',
  PHP = 'PHP',
  PLN = 'PLN',
  GBP = 'GBP',
  QAR = 'QAR',
  CNY = 'CNY',
  OMR = 'OMR',
  RON = 'RON',
  RUB = 'RUB',
  RWF = 'RWF',
  SHP = 'SHP',
  WST = 'WST',
  SAR = 'SAR',
  RSD = 'RSD',
  SCR = 'SCR',
  SLL = 'SLL',
  SGD = 'SGD',
  SBD = 'SBD',
  SOS = 'SOS',
  ZAR = 'ZAR',
  KRW = 'KRW',
  LKR = 'LKR',
  SRD = 'SRD',
  SEK = 'SEK',
  CHF = 'CHF',
  TJS = 'TJS',
  TZS = 'TZS',
  THB = 'THB',
  TOP = 'TOP',
  TTD = 'TTD',
  TND = 'TND',
  TRY = 'TRY',
  TMT = 'TMT',
  AED = 'AED',
  UGX = 'UGX',
  UAH = 'UAH',
  UYU = 'UYU',
  USD = 'USD',
  UZS = 'UZS',
  VUV = 'VUV',
  VND = 'VND',
  XOF = 'XOF',
  YER = 'YER',
  ZMW = 'ZMW',
}